library(peer)
expr = read.csv('./expression.csv', header=FALSE)
model = PEER()
PEER_setPhenoMean(model,as.matrix(expr))
PEER_setNk(model,10)
PEER_getNk(model)
PEER_update(model)
PEER_setAdd_mean(model, TRUE)
PEER_setNmax_iterations(model, 1000)
PEER_setTolerance(model,1)
PEER_setVarTolerance(model,0.1)
PEER_setPriorAlpha(model,0.001,0.1)
PEER_setPriorEps(model,0.1,10)
factors = PEER_getX(model)
weights = PEER_getW(model)
precision = PEER_getAlpha(model)
residuals = PEER_getResiduals(model)
write.table(factors,"peer.txt",quote=F,row.names=F,col.names=F,sep="\t")
